export const TEACHER_SCHEDULE_FETCH_REQUEST = 'api/TEACHER_SCHEDULE_FETCH_REQUEST'
export const TEACHER_SCHEDULE_FETCH_SUCCESS = 'api/TEACHER_SCHEDULE_FETCH_SUCCESS'
export const TEACHER_SCHEDULE_FETCH_FAILURE = 'api/TEACHER_SCHEDULE_FETCH_FAILURE'

export const GEO_INFO_FETCH_REQUEST = 'api/GEO_INFO_FETCH_REQUEST'
export const GEO_INFO_FETCH_SUCCESS = 'api/GEO_INFO_FETCH_SUCCESS'
export const GEO_INFO_FETCH_FAILURE = 'api/GEO_INFO_FETCH_FAILURE'